version: 2

updates:
  # Dashboard
  - package-ecosystem: npm
    directory: /Dashboard
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  # Bot
  - package-ecosystem: npm
    directory: /Bot
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
